version: "2"

checks:
  argument-count:
    enabled: true

  complex-logic:
    enabled: true

  file-lines:
    enabled: true

  method-complexity:
    enabled: true

  method-count:
    enabled: true

  method-lines:
    enabled: true

  nested-control-flow:
    enabled: true

  return-statements:
    enabled: true

  similar-code:
    enabled: true

  identical-code:
    enabled: true

plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          patterns:
            - test/*.js

  csslint:
    enabled: true

  eslint:
    enabled: true

  fixme:
    enabled: true

  nodesecurity:
    enabled: true

  markdownlint:
    enabled: true

  shellcheck:
    enabled: true

exclude_patterns:
  - .nyc_output/**
  - node_modules/**
  - coverage/**
